#include "../header/4_2_strings.h"
#include "../header/1_1_hello.h"
#include "../header/4_4_instr2.h"
#include "../header/4_7_string1.h"
#include "../header/4_11_structur.h"
#include "../header/4_17_use_new.h"
#include "../header/4_17_2_use_delete.h"
#include "../header/4_18_arraynew.h"
#include "../header/4_20_ptrstr.h"
#include "../header/4_21_newstrct.h"
#include "../header/5_14_waiting.h"
#include "../header/5_17_textin2.h"
#include "../header/5_18_textin3.h"
#include "../header/6_13_cinfinish.h"
#include "../header/6_14_cingolf.h"
#include "../header/6_15_outfile.h"
#include "../header/6_16_sumafile.h"
#include "../header/7_5_arrfun1.h"
#include "../header/7_7_arrfun3.h"
#include "../header/7_10_strgback.h"
#include "../header/7_15_arrfun.h"
#include "../header/7_18_func_ptr.h"
#include "../header/8_8_filefunc.h"
#include "../header/8_13_special_template.h"
#include "../header/9_5_external.h"
#include "../header/9_7_namespace_demo.h"
#include "../header/9_12_namesp_excut.h"
#include "../oop/excute/header/10_1_usestock.h"
#include "../oop/excute/header/11_1_usetime.h"
#include "../oop/excute/header/11_13_usevector.h"
#include "../oop/excute/header/12_1_usestring.h"
#include "../oop/excute/header/12_9_placenew.h"
#include "../oop/excute/header/13_1_usetabten.h"
#include "../oop/excute/header/13_9_usebrass.h"
#include "../header/14_1_valarray.h"
#include "../oop/excute/header/14_7_useworker.h"
#include "../oop/excute/14_13_usestacktp.h"
#include "../oop/class/template/pairs/14_19_pairs.h"
#include "../oop/class/template/friend/14_22_template_friend.h"
#include "../oop/friend/tv/use_tv.h"
#include "../oop/friend/sync/15_1_4_sync.h"
#include "../error/15_7_error.h"
#include "../error/15_12_error.h"
#include "../error/sales/15_14_sales.h"
#include "../rtti/rtti1.h"
#include "../string/16_1_str1.h"
#include "../string/16_2_strfile.h"
#include "../string/16_4_str2.h"
#include "../string/16_5_smrtptrs.h"
#include "../stl/vect1.h"
#include "../stl/16_9_vect3.h"
#include "../stl/16_14_multimap.h"
#include "../stl/16_15_functor.h"
#include "../stl/16_17_strgst1.h"
#include "../stl/16_20_valvect.h"

int main() {

//    sayHello();
//    learnString();
//    getInputLine();
//    getInputString();
//    learnStructur();
//    use_new();
//    use_delete();
//    new_array();
//    ptrstr();
//    newstrct();
//    waiting();
//    textin2();
//    textin3();
//    cinfinish();
//    cingolf();
//    outfile();
//    sumafile();
//    arrfun1();
//    arrfun3();
//    strgback();
//    arrfun();
//    func_ptr();
//    filefunc();
//    special_template();
//    external_demo();
//    namespace_demo();
//    namesp_excut();
//    usestock0();
//    usestock1();
//    usetime();
//    usevector();
//    usestring();
//    placenew();
//    usetabten();
//    usebrass1();
//    use_valarray();
//    useworker();
//    usestacktp();
//    usepairs();
//    use_template_friend();
//    use_tv();
//    use_sync();
//    error_demo4();
//    use_sales();
//    use_rtti1();
//    use_str1();
//    use_strfile();
//    use_str2();
//    use_smrtptrs();
//    use_vect3();
//    use_mltimap();
//    use_functor();
//    use_strgst1();
    use_valvect();

    return 0;
}